- name: install and run nginx server
  hosts: web
  tasks:
  - name: install nginx server
    ansible.builtin.package:
      name: nginx
      state: present

  - name: run nginx server
    ansilbe.builtin.service:
      name: nginx
      state: started
      enabled: yes