- name:
  hosts: local
  connection: local
  vars:
    course: "Devops with AWS" # String
    duration: 120 #number
    content: #list
      - abcd
      - efgh
      - ijkl
      - mnop
      - qrst
    live: true #boolean
    tools: #map
      cloud: AWS
      cm: ansilbe

  tasks:
    - name: print all data types
      ansible.builtin.debug:
        msg: " course is {{course}}, duration is {{duration}}, contents are {{contents}}, is it live{{live}},tools include {{tools}}"
