- name: given number is less than or greater than
  hosts: local
  connection: local
  vars:
    x: 10
  vars_prompt:
    - name: y
      prompt: enter the number y
      private: false
  tasks:
    - name: check number is greater than
      ansible.builtin.debug:
        Z: " {{ y | int }}"
        msg: " given {{x}} is grater than {{Z}} "
      when: x > Z

    - name: check number is less than
      ansible.builtin.debug:
        Z: " {{ y | int }}"
        msg: " given {{x}} is less than {{Z}}"
      when : x < Z