- name: conditions
  hosts: local
  connection: local
  tasks:
    - name: install nginx in RHEL
      ansilbe.builtin.dnf:
        name: nginx
        state: installed
        msg: "nginx installed in RHEL"
      when: ansible_os_family = "RHEL"

    - name: install nginx in ubuntu
      ansible.builtin.apt:
        name: nginx
        state: installed
        msg: " nging installed in ubuntu"
      when: ansible_os_family = "ubuntu"