- name: install packages
  hosts: web
  connection: local
  tasks:
    - name: install packages
      ansible.builtin.package:
        name: " install {{ item }}"
        state: installed
      loop:
        - gcc
        - zip
        - mysql
        - nginx