- name: install nginx
  hosts: local
  connection: local
  tasks:
    - name: install nginx
      ansible.builtin.package:
      name: " install {{ item.name }}"
      state: " installed "{{ item.state}}""
      loop:
        - name: "gcc" state: "presnet"
        - name: "nginx" state: "absent"
        - name: "zip" state: " present"
