- name: install nginx
  hosts: web
  connection: local
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.package:
        name: "{{ item.name }}"
        state:  "{{ item.state }}"
      loop:
      - { name: 'gcc', state: 'present'}
      - { name: 'nginx', state: 'absent'}
      - { name: 'zip', state: 'present'}
