- name: install nginx
  hosts: web
  connection: local
  connection: local
  tasks:
    - name: install nginx
      ansible.builtin.package:
      name: " install {{ item.name }}"
      state:  "{{ item.state}}"
      loop:
        - name: "gcc" state: "present"
        - name: "nginx" state: "absent"
        - name: "zip" state: " present"
