- name: shell vs command
  hosts: web
  connection: local
  tasks:
    - name: execute ls command
      # ansible.builtin.command: ls -lrth > /tmp/output.txt
      ansible.builtin.shell: ls -lrth > /tmp/output.txt
