- name: creating ec2 instance
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: install python libraries
      ansible.builtin.pip:
        name: "{{ item }}"
        state: present
        executable: pip3.9
      loop:
      - botocore
      - boto3

    - name: creating ec2 instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        vpc_subnet_id: subnet-06b401e93006806d8
        instance_type: t3.micro
        image_id: ami-09c813fb71547fc4f
        security_group: sg-000e29e59ac2e3185
        # termination_protection: true
        # wait: true
      loop:
      - mysql
      - frontend
      - backend